### ISSUE TITLE
Transitioning from Yii Rights

### ISSUE THREAD

**Issue by NathanHazout** [cniska/yii-auth#1]
Is this extension production ready?
Is it better to use this one vs Yii Rights?

If the answer is yes to both, could you post a Wiki with a tutorial on how to transition from Yii Rights to Yii Auth?

My project is still young so if Yii Auth is the way to go, I could transition.

**Comment by cniska** [comment]
Yes and probably yes. Auth  has a bit less features than Rights but its code base is a lot better. Transitioning from Rights should just be to download, unpack, configure and start using Auth. Because Auth doesn't require you to extend any of its classes you should change to use CDbAuthManager, CController, CWebUser, etc. instead of those bundled by Rights.

**Comment by raoul2000** [comment]
I successfully switched from "Rights" to "Auth", but ok, I was not using all the features provided by Rights. The only thing I had to modify is **Yii:app()->user->isSuperUser** which is implemented in **RWebUser**.

So to not have to modify all calls to isSuperUser, here is how I modified my WebUser class :

``` php
class WebUser extends CWebUser {

    public function afterLogin($fromCookie)
    {
        parent::afterLogin($fromCookie);
        // the super user list is the one configured
        // for the Auth module.... so check if username in defined
        // in this array
        $superUsers = Yii::app()->getModule('auth')->users;
        if( in_array($this->getName(), $superUsers)){
            $this->isSuperuser = true;
        }
    }
    /**
    * @param boolean $value whether the user is a superuser.
    */
    public function setIsSuperuser($value)
    {
        $this->setState('Auth_isSuperuser', $value);
    }
    /**
    * @return boolean whether the user is a superuser.
    */
    public function getIsSuperuser()
    {
        return $this->getState('Auth_isSuperuser');
    }
}
```

**Comment by raoul2000** [comment]
The method CWebUser->checkAccess() should also be modified as RWebUser always granted access to the super User.

**Comment by NathanHazout** [comment]
What about the database schema? Is it the same?

**Comment by cniska** [comment]
Auth itself doesn't have a db schema but you will need the tables for
CDbAuthManager.

**Comment by cniska** [comment]
I added similar functionality in version 1.3.0.
