### ISSUE TITLE
AuthWebUser and its behaviors do not have a method or closure named "updateSession". 

### ISSUE THREAD

**Issue by larry-tx** [cniska/yii-auth#100]
I am trying to replace the "Rights" module with the Yii-Auth module. I also have the Yii-User module installed (with a version ID of UserModule.php 132 2011-10-30 10:45:01Z mishamx). I've done the configuration just as you've stated in your directions. However, when I attempt to login, I get an error message that states: AuthWebUser and its behaviors do not have a method or closure named "updateSession". 

"updateSession" is called in the user model's afterSave.

Any ideas on how to deal with this? I know that in the past we had to substitute RWebUser for WebUser, but your directions for Yii-Auth don't include that.

**Comment by cniska** [comment]
This is probably related to the fact that yii-user and Auth does not play well together, there was a PR to fix this but I rejected it since I do not like to include module specific fixes, it tends to reduce the code quality.
