### ISSUE TITLE
CachedDbAuthManager not work - error

### ISSUE THREAD

**Issue by magefad** [cniska/yii-auth#13]
include(ICachedAuthManager.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory

Catch error in other module using yii filters function...

**Comment by ghost** [comment]
Same here.
Could not find the problem: file exists and rights are ok (Linux).

My temporary fix: 

``` php
# class CachedDbAuthManager extends CDbAuthManager implements ICachedAuthManager
class CachedDbAuthManager extends CDbAuthManager
```

Works so far...

**Comment by magefad** [comment]
Temporary write 

``` php
Yii::import('auth.components.ICachedAuthManager');
```

**Comment by ghost** [comment]
Works fine too. Thanks.
