### ISSUE TITLE
Admin role makes no sense

### ISSUE THREAD

**Issue by magefad** [cniska/yii-auth#14]
In rights module admin rba role grant full access to all operations.

Why here full access is given only through user component config? Is this correct?

**Comment by cniska** [comment]
I refactored to the code to check if the user is an administrator through the user component before letting them into the module. I hope it makes more sence now.

**Comment by magefad** [comment]
I mean that in a module rights was the role of the administrator, which gave access to all operations.
Now, administrators are appointed only by the configuration in the file (main.php etc), not in the module (through its interface)
