### ISSUE TITLE
PHP error include(AuthModule.php) using filter in controller

### ISSUE THREAD

**Issue by magefad** [cniska/yii-auth#15]
``` php
throw new CHttpException(401, Yii::t('AuthModule.main', 'Access denied.'));
```

include(AuthModule.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory

You can add an import 

``` php
    'import'            => array(
        ...
        'application.modules.auth.AuthModule'
    ),
```

But I think it's an ugly solution?

Can be attributed to a bug of yii framework, as it is not clear why we need to use the import module file to use Yii:t() function

**Comment by cniska** [comment]
I've fixed this by removing the call to Yii::t() for now.
