### ISSUE TITLE
No design

### ISSUE THREAD

**Issue by NathanHazout** [cniska/yii-auth#2]
![Screen Shot 2013-01-02 at 10 47 52 AM](https://f.cloud.github.com/assets/329834/37904/25575708-54b9-11e2-871e-e91b67554869.png)

This is what it looks like for me.
Note that  I installed Bootstrap for this extension, but I don't use it anywhere in my layout files. So I'm not sure if it's supposed to work out of the box.

**Comment by cniska** [comment]
Hey Nathan,

You need to call the Bootstrap's register method or include its styles some
other way.

-Chris

On Wed, Jan 2, 2013 at 10:49 AM, Nathan Hazout notifications@github.comwrote:

> [image: Screen Shot 2013-01-02 at 10 47 52 AM]https://f.cloud.github.com/assets/329834/37904/25575708-54b9-11e2-871e-e91b67554869.png
> 
> This is what it looks like for me.
> Note that I installed Bootstrap for this extension, but I don't use it
> anywhere in my layout files. So I'm not sure if it's supposed to work out
> of the box.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Crisu83/yii-auth/issues/2.

## 

Best regards,
Christoffer Niska
Phone +358 500 980 565
E-mail ChristofferNiska@gmail.com

**Comment by NathanHazout** [comment]
Where? As of now I don't plan to use Bootstrap anywhere else than for this extension (although maybe later if needed). 
I did all that was asked in the Bootstrap setup (http://www.cniska.net/yii-bootstrap/setup.html), except for including the "theme" in my main.php because it broke the entire site.
Funnily, it broke my site's design but the Auth module kept my original design (and still didn't display correctly).

**Comment by cniska** [comment]
You can create a custom layout that includes bootstrap and configure the
module to use it.
