### ISSUE TITLE
composer support

### ISSUE THREAD

**Issue by schmunk42** [cniska/yii-auth#25]
I've raised a similar request for yii-bootstrap a while ago here: https://bitbucket.org/Crisu83/yii-bootstrap/pull-request/30/info-file-for-composer/diff

Would be nice if you could think about including composer.json files again - I'll send you a pull-request if you want to - since extension dependencies are becoming more and more important.

Just as an example: yii-auth depends on yii-bootstrap (which may also depend on twitter/bootstrap) and both depend on yiisoft/yii.

**Comment by cniska** [comment]
Hey,

Sure. It would be nice if you could make a similar pull request for
yii-bootstrap as well. I'm about to move yii-bootstrap development to
GitHub as well. Probably when I've made the necessary changes to make it
play nicely with yiibooster.

**Comment by schmunk42** [comment]
Nice to hear that :)

I'll send you a pull request for yii-auth. Let me know when you're ready on github with yii-bootstrap (I've send you my e-mail via Skype).
As mentioned above I would say that yii-auth depends on yii-bootstrap and yii.

Note: For getting the composer thing to work you'd either have to submit yii-auth to http://packagist.org or enable the repo http://packages.phundament.com in your composer config.

What's about YiiBooster? I thought it has the same class names. Will it just include (depend on) yii-bootstrap in the future?

**Comment by cniska** [comment]
The plan is to make YiiBooster extend the Bootstrap extension. We're
discussing the details with Antonio later this week.

On Mon, Jan 21, 2013 at 9:28 PM, Tobias Munk notifications@github.comwrote:

> Nice to hear that :)
> 
> I'll send you a pull request for yii-auth. Let me know when you're ready
> on github with yii-bootstrap (I've send you my e-mail via Skype).
> As mentioned above I would say that yii-auth depends on yii-bootstrap and
> yii.
> 
> Note: For getting the composer thing to work you'd either have to submit
> yii-auth to http://packagist.org or enable the repo
> http://packages.phundament.com in your composer config.
> 
> What's about YiiBooster? I thought it has the same class names. Will it
> just include (depend on) yii-bootstrap in the future?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Crisu83/yii-auth/issues/25#issuecomment-12513359.

## 

Best regards,
Christoffer Niska
Phone +358 500 980 565
E-mail ChristofferNiska@gmail.com

**Comment by schmunk42** [comment]
Would be nice, if you could you also raise the composer topic there.
Let me know if there are questions.

**Comment by cniska** [comment]
Feel free to make a pull request for the composer.json file.

**Comment by schmunk42** [comment]
You may have to add some values ...

./composer.json is valid, but with a few warnings
See http://getcomposer.org/doc/04-schema.md for details on the schema
License "-" is not a valid SPDX license identifier, see http://www.spdx.org/licenses/ if you use an open license
authors.0.email : invalid value (-), must be a valid email address

With a composer.json file you can also submit yii-auth to https://packagist.org
