### ISSUE TITLE
Minor bug: translation-issue

### ISSUE THREAD

**Issue by fierwebdesign** [cniska/yii-auth#3]
I discovered a minor bug. On several places the type of an authorisation-item is translated into its proper name (by means of the AuthController->getItemTypeText function). When this is done, and the result is used in a link (as is done in some grid-views troughout the module), it will render some dead-end links in a translated module. It then links to a controller based on the translation, which of course doesn't exist.
The solution I myself came up with was to add an extra function to authController, to use in the links:

```
public function getItemTypeController($type)
{
    switch ($type)
    {
        case CAuthItem::TYPE_OPERATION:
            $controller = 'operation';
            break;

        case CAuthItem::TYPE_TASK:
            $controller = 'task';
            break;

        case CAuthItem::TYPE_ROLE:
            $controller = 'role';
            break;

        default:
            throw new CException('Auth item type "' . $type . '" is valid.');
    }

    return $controller;
}
```

**Comment by cniska** [comment]
Thanks for noticing this issue. Any chance that you could create a pull request for this change? I'd accept it with a few minor modifications.
