### ISSUE TITLE
The page isn't redirecting properly

### ISSUE THREAD

**Issue by tahiryasin** [cniska/yii-auth#36]
After enabling module it shows me "The page isn't redirecting properly" and site is no longer accessible.

Here is config file http://codepad.org/ux4fCtEm

and here main controller class http://codepad.org/GFoPJn1s

**Comment by softark** [comment]
I think it's because you have not allowed the guests (anonymous users) to access the login page.

**Comment by tahiryasin** [comment]
@softark thanks for your reply but that is what I want to know, can you please tell me how can I allow guests for some actions?

**Comment by softark** [comment]
Probably you have to do the following:
1. Create a role 'guest' for the guest users.
2. Define 'guest' as a default role.
3. Create an operation 'site.login' for the login page. ... I assume that your login page is 'in 'site' controller and the action is 'login'.
4. Add 'site.login' operation as a child to 'guest' role.

**Comment by mve-it-solutions** [comment]
How do you define role 'guest' as default role? I can't use defaultRoles in main.php within array authManager

**Comment by softark** [comment]
As you see in the guide, you can define the default roles in the config file.
http://www.yiiframework.com/doc/guide/1.1/en/topics.auth#using-business-rules

And, well, I think the 'guest' role won't need a business rule, because everyone should have the rights as a guest.

**Comment by softark** [comment]
Ah, I've found another simple solution in a comment of auth extension.
You can just exclude the actions for the guests from the filter.

```
public function filters()
{
    return array(
        array('auth.filters.AuthFilter - login, test'),
    );
}
```

http://www.yiiframework.com/extension/auth/#c11979

**Comment by mve-it-solutions** [comment]
I mean, this won't work
[protected/config/main.php]

<pre><code>
        'authManager'=>array(
            'defaultRoles'=>array('guest'),
            'behaviors' => array(
                array(
                    'class'=>'auth.components.AuthBehavior',
                    'admins' => array('admin'), // a list of users who has access to the module.
                ),
            ),
        ),
</code></pre>

[protected/components/controller.php]
add:

<pre><code>
    public function filters()
    {
        return array(
            array('auth.filters.AuthFilter'),
        );
    }
</code></pre>

add role guest using yii-auth with operation site.*
operation user.login.\* (yii-user module)

I get error:
Error 310 (net::ERR_TOO_MANY_REDIRECTS): There were too many redirects.

**Comment by softark** [comment]
Sorry, I think this "issue" should be closed.
This is not a good place for discussing this kind of problems. The forum is more appropriate for them.

**Comment by mve-it-solutions** [comment]
This did the trick https://github.com/Crisu83/yii-auth/pull/53.
Thanks m-nel ;-)
