### ISSUE TITLE
custom user class

### ISSUE THREAD

**Issue by manuel-84** [cniska/yii-auth#41]
I'm using a custom User's class and I can't use the built-in AuthWebUser

So I added the checkAccess method to my class and in AuthModule.php, line 114, I propose to add checks for methods instead of having only the name of the class

``` php

if ($user instanceof AuthWebUser || method_exists($user, 'getIsAdmin'))
```

**Comment by cniska** [comment]
Why don't you extend your custom class from AuthWebUser?

**Comment by manuel-84** [comment]
it could work but it's not much logic to extend the main user class of my app from a specific module class :/
and more... my isAdmin function have nothing to do related to the admins of the auth module

**Comment by cniska** [comment]
You are correct, the isAdmin could be a behavior but we cannot bypass to
checkAccess call by using a behavior.

On Mon, Feb 18, 2013 at 10:33 PM, Manuel notifications@github.com wrote:

> it could work but it's not much logic to extend the main user class of my
> app from a specific module class :/
> and more... my isAdmin function have nothing to do related to the admins
> of the auth module
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Crisu83/yii-auth/issues/41#issuecomment-13741633.

## 

Best regards,
Christoffer Niska
Phone +358 500 980 565
E-mail ChristofferNiska@gmail.com

**Comment by manuel-84** [comment]
in my case first I tried to rename the function to isAuthAdmin then I completely deleted the need of this function keeping in AuthModule the check for this

``` php
if (in_array($user->{$this->userNameColumn}, Yii::app()->authManager->admins)) return true;
```

the only thing is that I suppose that we have a webuser class where we can retrieve the "userNameColumn" value

**Comment by manuel-84** [comment]
actually I edited AuthModule like this

``` php
    public function beforeControllerAction($controller, $action)
    {
        if (parent::beforeControllerAction($controller, $action))
        {
            if ($this->userIsAdmin()) return true;
        }
        throw new CHttpException(401, Yii::t('AuthModule.main', 'Access denied.'));
    }

  public function userIsAdmin() {
    $user = Yii::app()->getUser();
    if (in_array($user->{$this->userNameColumn}, Yii::app()->authManager->admins)) return true;
    else return false;
  }
```

and to let me search for users in the AssignmentController I changed the actionIndex to use the user specified class instead of the dataProvider

``` php
    /**
     * Displays the a list of all the assignments.
     */
    public function actionIndex()
    {
        //$dataProvider = new CActiveDataProvider($this->module->userClass);
    $model = CActiveRecord::model($this->module->userClass);
    $model->unsetAttributes(); // clear any default values
    if (Yii::app()->request->getParam($this->module->userClass) != null)
      $model->attributes = Yii::app()->request->getParam($this->module->userClass);

        $this->render('index', array(
            'model' => $model //$dataProvider
        ));
    }
```

and ofc the view use $model instead of $dataProvider

``` php
  'filter' => $model,
  'dataProvider' => $model->search(),
```
