### ISSUE TITLE
Unauthenticated user

### ISSUE THREAD

**Issue by m-nel** [cniska/yii-auth#52]
Once the filter is implemented, allowing an unauthenticated user to perform certain actions is not possible.

A possible use case:
- object.view
  - Displays information about the object
- object.admin
  - Manage the object

Scenario: we want unauthenticated users to be able to view the object, but not to manage it. 

With the code as is, this is not possible.

Solution: 
1. Create a role "unauthenticated"
2. Assign object.view permissions to that role
3. In config, make "unauthenticated" a default role [Yii Docs](http://www.yiiframework.com/doc/guide/1.1/en/topics.auth#using-default-roles)
4. Edit filters.AuthFilter (Will commit this soon)

**Comment by mve-it-solutions** [comment]
Thanks, https://github.com/Crisu83/yii-auth/pull/53 helped me solve my issues with defining guest role as default role.

**Comment by ametad** [comment]
What about this:

``` php
    public function filters()
    {
        return array(
            array('auth.filters.AuthFilter - login, logout, restore, captcha, error'),
        );
    }
```

(source: http://www.yiiframework.com/extension/auth#c12011)

This syntax allows the declaration of actions not te be checked.

**Comment by m-nel** [comment]
@ametad 
Thanks that certainly works, although, there are/could be scenarios where this is just not sufficient.
As an example: 
I want to set cron jobs that would execute code based on a schedule. This requires me to make the action public to all. As a large amount of these actions are lengthy processes, that opens me up to DOS attacks. 
Some of these actions send out emails to users, axiomatically I do not wish to have all these actions open to the public. 

The solution? A default role with a bizrule, that is only applied if the request originates from the localhost, i.e. the server.

Another example; this "quirk" does not allow the use of [RunActions](http://www.yiiframework.com/extension/runactions/). Since the implementation of runactions perform unauthenticated requests on actions.

**Comment by cniska** [comment]
If I understand this correctly this issue is already fixed as I merged the PR from m-nel.
