### ISSUE TITLE
TbHtml

### ISSUE THREAD

**Issue by softark** [cniska/yii-auth#59]
There's no TbHtml.php yet.

views\assignment\view.php(55):
54             <?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
55                 'type' => TbHtml::FORM_INLINE,
56             )); ?>

**Comment by cniska** [comment]
Yes there is. Auth has been updated to use the next gen of yii-bootstrap,
yiistrap http://github.com/yii-twbs/yiistrap

-Christoffer

**Comment by cniska** [comment]
If you want to use yii-bootstrap downgrade to a previous version of Auth.

-Christoffer

**Comment by softark** [comment]
I see. I didn't know the repository of yii-twbs !! Thanks.
