### ISSUE TITLE
Update yii-auth to the newest yiistrap

### ISSUE THREAD

**Issue by waitekk** [cniska/yii-auth#74]
Currently there are multiple issues with `TbHtml` constants, which were altered in (this commit)[https://github.com/Crisu83/yiistrap/commit/e3249ec72b8b995c31272f92a8795d46f3f259d4]

**Comment by cniska** [comment]
I'm aware of this, I'll fix it as soon as possible. The only problem is
that I'm very busy at work currently. Please use an older version for now.

On Sat, Jun 1, 2013 at 10:10 AM, waitekk notifications@github.com wrote:

> Currently there are multiple issues with TbHtml constants, which were
> altered in (this commit)[Crisu83/yiistrap@e3249echttps://github.com/Crisu83/yiistrap/commit/e3249ec72b8b995c31272f92a8795d46f3f259d4
> ]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Crisu83/yii-auth/issues/74
> .

## 

Best regards,
Christoffer Niska
Phone +358 500 980 565
E-mail ChristofferNiska@gmail.com

**Comment by waitekk** [comment]
Thank you, Chris.

**Comment by cniska** [comment]
If you want to help you can do a pull request for this.

**Comment by kachar** [comment]
Here is a pull request on the topic #80
