### ISSUE TITLE
How to add Bizrule from UI

### ISSUE THREAD

**Issue by saikiranvarma** [cniska/yii-auth#78]
Hi crisu83 i need to store biz rule while creating roles, tasks and operations.
How can i do it.

**Comment by cniska** [comment]
For now you have to add that functionality manually. I've explain why many
times, look at the previous issues.

On Thu, Jun 13, 2013 at 11:02 AM, saikiranvarma notifications@github.comwrote:

> Hi crisu83 i need to store biz rule while creating roles, tasks and
> operations.
> Hoe can i do it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Crisu83/yii-auth/issues/78
> .

## 

Best regards,
Christoffer Niska
Phone +358 500 980 565
E-mail ChristofferNiska@gmail.com
