### ISSUE TITLE
Yii-auth and yii strap

### ISSUE THREAD

**Issue by DrMabuse23** [cniska/yii-auth#82]
Hi,
i use Yii-auth with Yii-strap and got this error 

Fatal error: Undefined class constant 'STYLE_LINK' in common/lib/vendor/crisu83/yii-auth/widgets/AuthAssignmentRevokeColumn.php on line 36

How to solve this ?

**Comment by Darkheir** [comment]
I have the same with :

> PHP Fatal error:  Undefined class constant 'STYLE_PRIMARY'  in protected/modules/auth/views/authItem/index.php

I checked the code, the constant its trying to call is `TbHtml::STYLE_PRIMARY` but this constant isn't present in the `TbHtml` class!

**Comment by cniska** [comment]
You need to downgrade yiistrap or update auth views. If you decide to downgrade you can use the old repo at http://github.com/yii-twbs/yiistrap/
