### ISSUE TITLE
Problem in set-up and running the auth extension

### ISSUE THREAD

**Issue by Lanzjess** [cniska/yii-auth#84]
I downloaded the extension and copied the configuration. I have already set-up the auth tables. But it still doesn't work. I can't access the auth UI in http://localhost/project/index.php/auth I can't get any error.
I also tried the http://localhost/project/index.php/auth/operation/index
and http://localhost/project/index.php/auth/assignment/index.

In the AuthAssignment table I have set the user as the role admin.

This is my configuration in main.php:
/_For modules_/
'modules' => array(
        'auth'=> array(
                    'strictMode' => true, // when enabled authorization items cannot be assigned children of the same type.
                    'userClass' => 'User', // the name of the user model class.
                    'userIdColumn' => 'id', // the name of the user id column.
                    'userNameColumn' => 'username', // the name of the user name column.
                  // 'appLayout' => 'application.views.layouts.main', // the layout used by the module.
                    'defaultLayout' => 'application.views.layouts.main', // the layout used by the module.
                    'viewDir' => null, // the path to view files to use with this module.
               ),
//..

```
 // application components
```

'components' => array(
//..
 'authManager' => array(
            'class'=>'CDbAuthManager',
                 'connectionID'=>'db',
             //            /\* Renaming tables*/
            'assignmentTable' => 'AuthAssignment',
            'itemTable' => 'AuthItem',
            'itemChildTable' => 'AuthItemChild',
            //'defaultRoles'=>array('dataConsumer'),
            'showErrors'=>true,
           'behaviors' => array(
             'auth' => array(
               'class' => 'auth.components.AuthBehavior',  
             ),
           ),
     ),
    'user' => array(
      'class' => 'auth.components.AuthWebUser',
     // 'admins' => array('admin', 'foo', 'bar'), // users with full access
        'admins' => array('admin')
    ),
//.. 
Can you shed some light on here? Thanks!

**Comment by cniska** [comment]
You should ask in the forum thread instead of creating an issue here.
