### ISSUE TITLE
Missing menu in assignment and authitem when use with yiistrap

### ISSUE THREAD

**Issue by mve-it-solutions** [cniska/yii-auth#86]
I miss this piece of code in auth/views/assignment/index and auth/views/authitem/index

```
<?php $this->widget('bootstrap.widgets.TbNav', array(
    'type' => TbHtml::NAV_TYPE_TABS,
    'items' => $this->menu,
)); ?>
```

If not set defaultLayout in main.php, default is used application.views.layouts.main.
When set defaultLayout to use the layout of auth.....this messes up the layout ;-)

**Comment by cniska** [comment]
The reason why it isn't in the views is because some apps might want to have their secondary navigation somewhere else and Auth actually allows for this. This is not a bug, but we should fix the default layout if it's broken.
