### ISSUE TITLE
how can without ForeignKey it's a big problem for mysql dump

### ISSUE THREAD

**Issue by djfly** [cniska/yii-auth#87]
I really can not stand, foreign key associations, always insert data errors, or export errors, errors in short everywhere, foreign keys, really not a good thing, excluding foreign keys, please

**Comment by cniska** [comment]
I use foreign keys all the time and you should too. You can always disable them when you want to drop something.

**Comment by djfly** [comment]
#1701 - Cannot truncate a table referenced in a foreign key constraint (`cms`.`authitemchild`, CONSTRAINT `authitemchild_ibfk_1` FOREIGN KEY (`parent`) REFERENCES `cms`.`authitem` (`name`))

**Comment by djfly** [comment]
错误

SQL 查询:

 INSERTINTO`authitemchild` 
VALUES (

 'moderators','manage_posts'
);

MySQL 返回： 
#1452 - Cannot add or update a child row: a foreign key constraint fails (`cms`.`authitemchild`, CONSTRAINT `authitemchild_ibfk_1` FOREIGN KEY (`parent`) REFERENCES `authitem` (`name`) ON DELETE CASCADE ON UPDATE CASCADE)

**Comment by cniska** [comment]
Try running this before running truncate: "SET foreign_key_checks = 0;"
