### ISSUE TITLE
属性 "User.id" 未被定义

### ISSUE THREAD

**Issue by huangcongg** [cniska/yii-auth#91]
属性 "User.id" 未被定义，
it means User.id is undefined. I don't know how to modify.

it is below:
/var/www/html/myxk/protected/modules/auth/widgets/AuthAssignmentNameColumn.php(34): CActiveRecord->__get("id")

29      \* @param integer $row the row number (zero-based).
30      \* @param mixed $data the data associated with the row.
31      */
32     protected function renderDataCellContent($row, $data)
33     {
34         echo CHtml::link(CHtml::value($data, $this->nameColumn), array('view', 'id' => $data->{$this->idColumn}));
35     }
36 }

**Comment by huangcongg** [comment]
I see. I make a stupid mistake.

**Comment by cniska** [comment]
Seems like this was no issue in the first place.
