### ISSUE TITLE
Set Admin based in ID instead of Name

### ISSUE THREAD

**Issue by Okeanos** [cniska/yii-auth#95]
I believe it would be a good idea to allow IDs instead of names to be used to set admin status via the config.

The ID column has to be specified already and by its very nature is guaranteed to be unique. Of course one can _assume_ that the name is unique, however, depending on the implementation and origin this is not a given.

**Comment by cniska** [comment]
This is outside of the scope of this extension as it simply provides an ui for yii's built in authorization manager. I agree that this would be better but for now we're stuck with what yii provides.

**Comment by Okeanos** [comment]
Actually not … you manually set the admin state in `AuthWebUser()->init()` based on the `admins` array. I don't see Yii being involved there. Switching from names to IDs would be a matter of changing the value to test against, i.e. the ID column, and providing the correct array via the config. I am just wondering whether the ID column is actually available in that context.
Checking whether names or IDs have been supplied could probably be done fairly easy as well.
