### ISSUE TITLE
Postgres schema

### ISSUE THREAD

**Issue by offtza01** [cniska/yii-auth#98]
Please, tell me how to set database schema for this module. I can't find it :(

**Comment by cniska** [comment]
Is this what you are looking for? https://github.com/yiisoft/yii/blob/master/framework/web/auth/schema-pgsql.sql

**Comment by offtza01** [comment]
No, I'm acking how to set postgres schema for module. I've got 3 different schemas in database: "raports", "data" and "portal". Portal stores session and Auth tables . Unfortunetelly still have problem to find a way how go repair error:
SQLSTATE[42P01]: Undefined table: 7 Error: relation "AuthItem" doesn't exists
LINE 2: FROM "AuthItem"

I should be "portal"."AuthItem"

See no tableName() to change.

**Comment by cniska** [comment]
You need to set the `db` option to `portal` in your configuration for `CDbAuthManager` within your application config. See http://www.yiiframework.com/doc/api/1.1/CDbAuthManager for more details.

**Comment by cniska** [comment]
I assume that this issue was resolved?
