### ISSUE TITLE
Using Yii-Auth with Foundation

### ISSUE THREAD

**Issue by larry-tx** [cniska/yii-auth#99]
Is there any way to use this extension with Zurb Foundation and foundation4giix? I appreciate that you like Bootstrap, but I don't see why your preference for a particular CSS framework should dictate where your Auth extension can be used. What would it take to divorce the presentation part of your extension from the actual, relevant authorization part?

**Comment by cniska** [comment]
Sure you can, just implement your own views based on my Bootstrap based views.
